# Generated by Django 5.2.4 on 2025-08-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_commentlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(default=1, upload_to='attachments'),
            preserve_default=False,
        ),
    ]
